Operator chart: added nodeselector, affinity and tolerations
pravega/zookeeper-operator pull request #223
Opened 2020-07-30 14:47 UTC by efim-a-efim

### Change log description

Operator chart: added nodeSelector, affinity and tolerations support

### Purpose of the change

Adds support of scheduling parameters into operator chart.

### What the code does

Adds support of scheduling parameters into operator chart.

### How to verify it
1. Add nodeSelector, affinity or tolerations into operator chart values
2. After installing operator chart, check that they are applied

2020-08-10 13:13 UTC, SrishT commented
@efim-a-efim could u explain the purpose of adding these properties to the operator deployment manifest (also no default value has been configured for these properties i.e. nodeSelector, affinity and tolerations in the values.yaml)

2020-08-11 15:03 UTC, efim-a-efim commented
> @efim-a-efim could u explain the purpose of adding these properties to the operator deployment manifest

Yes. In our (and presumably in many other peoples) system we deploy operators to a dedicated namespace and a dedicated set of nodes - it's easier to manage. We use affinities to specify the nodes and taints/tolerations to prevent K8S from launching anything else on that nodes.

> (also no default value has been configured for these properties i.e. nodeSelector, affinity and tolerations in the values.yaml)
Yes, will add.

2020-08-19 13:42 UTC, SrishT requested changes

2020-08-19 13:42 UTC, SrishT commented on charts/zookeeper-operator/templates/post-install-upgrade-hooks.yaml
> +      {{- end }}
These parameters do not need to be added to the hook

2020-08-19 13:42 UTC, SrishT commented on charts/zookeeper-operator/templates/operator.yaml
> +      imagePullSecrets:
The imagePullSercret doesnt need to be added here. It has been configured into the service account.

2020-08-25 11:34 UTC, SrishT requested changes

2020-08-25 11:34 UTC, SrishT commented on charts/zookeeper-operator/templates/post-install-upgrade-hooks.yaml
> +      {{- end }}
As in previous case, please remove imagePullSecrets from here

2020-09-11 06:33 UTC, anishakj commented
@efim-a-efim  Could you please address the review comments.

2020-09-16 08:18 UTC, SrishT approved these changes
LGTM

2020-09-16 08:48 UTC, merged