support mutli images
pravega/zookeeper-operator pull request #230
Opened 2020-08-17 08:23 UTC by qixiaogang

### Change log description

Add image and volume array in the crd to support customize images deploy with zookeeper node.

### Purpose of the change
Support multi images, issue: https://github.com/pravega/zookeeper-operator/issues/228

2020-08-19 07:13 UTC, Prabhaker24 commented
@qixiaogang  can you please add the steps for verification in the pr?

2020-09-02 03:41 UTC, qixiaogang commented
@Prabhaker24  I doesn't get you about "the steps for verification in the PR", can you share more details?

and sorry for reply so late.

2020-09-10 05:21 UTC, qixiaogang commented
@Prabhaker24  Can you help with above comments

2020-09-10 05:30 UTC, Prabhaker24 commented
@qixiaogang sorry I got busy with some other stuff. What I mean is you have removed the sections **What the code does**  and **How to verify** from your pr description can you please add them back and explain what the code is doing there you can refer the following pr's description https://github.com/pravega/zookeeper-operator/pull/215, Thanks.

2020-09-11 03:16 UTC, qixiaogang commented
Thanks, get it.

2020-09-11 14:48 UTC, qixiaogang commented
@Prabhaker24  Add the **What the code does** and **How to verify**  back, please check

2020-09-13 17:43 UTC, Prabhaker24 approved these changes
LGTM

2020-09-14 02:08 UTC, qixiaogang commented
@anishakj  Can you help to review the PR, thanks

2020-09-14 05:08 UTC, anishakj requested changes
@qixiaogang  Could you please add the new fields in https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/README.md, and https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/README.md and https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/values.yaml

Also, since new parameters are added in spec ,CRD have to be changed to include the changes

2020-09-16 00:27 UTC, qixiaogang commented
@anishakj Add new scripts in the two files and update the crd

2020-09-16 05:13 UTC, anishakj approved these changes
LGTM

2020-09-16 05:16 UTC, merged