Issue 300: Zookeeper Operator pre-delete hook
pravega/zookeeper-operator pull request #301
Opened 2021-02-04 18:15 UTC by SrishT

Signed-off-by: SrishT <Srishti.Thakkar@dell.com>

### Change log description
Provides a pre-delete hook which ensures that custom resources are deleted before deleting the operator.

### Purpose of the change
Fixes #300 

### What the code does
Allows the operator to be deleted via helm only if the zookeepercluster custom resource has already been deleted, not otherwise.

### How to verify it
- If you try to delete the zookeeper operator before having deleted the zookeeper cluster resource, the pre-delete job will fail, thereby not allowing the operator from being deleted.
- If you try to delete the zookeeper operator after the zookeeper cluster resource has been cleaned up successfully, the operator will also be successfully deleted.

2021-02-08 14:46 UTC, jkhalack approved these changes
LGTM

2021-02-09 09:12 UTC, anishakj requested changes
Do we need to ensure role and role bindings deleted in addition to the cluster role?

2021-02-09 12:36 UTC, SrishT commented
> Do we need to ensure role and role bindings deleted in addition to the cluster role?

@anishakj we are only ensuring that the zookeepercluster custom resource has only been deleted before triggering the delete. We are not checking for the RBAC being already deleted since it is going to be deleted by this chart itself.

2021-02-09 12:43 UTC, anishakj approved these changes
LGTM

2021-02-09 12:51 UTC, merged