Issue 307: Provide a way for customization of annotations for service…
pravega/zookeeper-operator pull request #308
Opened 2021-03-01 12:40 UTC by alim-akbashev

### Change log description

A way for customization of annotations for services and for making LoadBalancer optional for AdminServer service has been added.

### Purpose of the change

Fixes #307 

### What the code does

- clientService, headlessService, adminServerService were added to CRD
- support of new objects added to generators.go
- new code covered with tests

### How to verify it

Adding annotations to clientService/headlessService/adminServerService should lead to attaching corresponding annotations to k8s Service's.
Adding `adminServerService.internal: true` should lead to creating k8s Service with ClusterIP without LoadBalancer.

2021-03-01 14:33 UTC, SrishT commented
Thank you for this PR @alim-akbashev. We will review it shortly.

2021-03-15 10:49 UTC, SrishT requested changes
The changes look good. The only problem is that the parameters within the charts have been added in a way that it fails with the following error if the annotations are left empty
```
Error: template: zookeeper/templates/zookeeper.yaml:91:18: executing "zookeeper/templates/zookeeper.yaml" at <.Values.clientService.annotations>: nil pointer evaluating interface {}.annotations
```
Please make changes such that it accounts for these fields being empty as well.

2021-03-16 10:17 UTC, alim-akbashev commented
thank you for review @SrishT! please advise me if could apply better fix.

2021-03-16 10:29 UTC, SrishT commented
> thank you for review @SrishT! please advise me if could apply better fix.

@alim-akbashev it might help to have an if check around the [clientService](https://github.com/pravega/zookeeper-operator/blob/ffc2b9fb04911af7b22dc394057424cfa1c55608/charts/zookeeper/templates/zookeeper.yaml#L90), [headlessService](https://github.com/pravega/zookeeper-operator/blob/ffc2b9fb04911af7b22dc394057424cfa1c55608/charts/zookeeper/templates/zookeeper.yaml#L95) and [adminServerService](https://github.com/pravega/zookeeper-operator/blob/ffc2b9fb04911af7b22dc394057424cfa1c55608/charts/zookeeper/templates/zookeeper.yaml#L100), like we have done in case of all other fields, so that that particular portion is populated only in case some value is specified for those fields by the user.

2021-03-16 10:53 UTC, alim-akbashev commented
makes sense, thanks!

2021-03-19 16:35 UTC, SrishT requested changes
Instead of exposing the AdminServer Service as an external loadbalancer service by default, it might be more desirable to expose it as an internal service. 
Also it might be better to specify the field in the following manner
```
adminServerService:
    external: false
    annotations: {}
```
where the default value of the field `adminServerService.external` would be false, so that even when the user does not provide any value for this field, it is exposed as an internal service by default.

2021-03-19 17:01 UTC, alim-akbashev commented
Definitely makes sense, i've thought about that as well, just tried to support current behaviour.
Anyway, will make it done on Monday, thanks!

2021-03-22 11:20 UTC, alim-akbashev commented
Done. `adminServerService.internal` has been replaced with `adminServerService.external` (false by default).
Unfortunately CI fails sometimes. It seems like that does not relate to changes in the PR since it fails on master branch as well (and has been failing few times on my branch, re-run helped that time):
```
image_pullsecret_test.go:56: 
        Unexpected error:
            <*errors.errorString | 0xc000113880>: {
                s: "timed out waiting for the condition",
            }
            timed out waiting for the condition
        occurred
```

2021-03-22 16:00 UTC, SrishT approved these changes
LGTM

2021-03-22 17:06 UTC, merged