Issue 338: CRD template refactor to accommodate different api versions
pravega/zookeeper-operator pull request #339
Opened 2021-05-29 06:31 UTC by lspecian-olx

### Change log description
In order to accommodate the both api versions schemas apiextensions.k8s.io/v1 and apiextensions.k8s.io/v1beta1 
- moved openAPIV3Schema as a named template in _helpers.tpl since the schema change moved the object 
- the schema change also moved the object additionalPrinterColumns which needed two versions as named templates since the attribute JSONPath was changed to jsonPath

### Purpose of the change

Closes #338 

### What the code does

The code is checking .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1" and adapting the template output accordingly to the support for the apiVersion 

### How to verify it

Chart is able to install in eks clusters that support both apiVersions apiextensions.k8s.io/v1 and apiextensions.k8s.io/v1beta1

2021-05-31 03:54 UTC, anishakj commented
@lspecian-olx , how you have generated  crd file? Is there any tools used

2021-05-31 07:21 UTC, lspecian-olx commented
> @lspecian-olx , how you have generated crd file? Is there any tools used

hello, I used only helm templates, not sure if I understood the question

2021-05-31 08:28 UTC, anishakj commented
> > @lspecian-olx , how you have generated crd file? Is there any tools used
> 
> hello @anishakj, I used only helm templates, not sure if I understood the question

Have you used any commands like `operatpr-sdk generate crds` ,but have seen that operator-sdk generate crd with `v1beta1` version

2021-06-03 03:46 UTC, anishakj commented
@lspecian-olx, could you please resolve the conflict?

2021-06-03 15:42 UTC, anishakj commented
@lspecian-olx  Looks like there is parse error after conflicts are resolved. Getting below error while try to install

```
Error: YAML parse error on zookeeper-operator/templates/zookeeper.pravega.io_zookeeperclusters_crd.yaml: error converting YAML to JSON: yaml: line 70: could not find expected ':'
```

2021-06-04 17:21 UTC, hansh0801 commented
thanks!

2021-06-04 20:00 UTC, SrishT requested changes
Just a very minor comment needs to be addressed, otherwise LGTM

2021-06-07 03:54 UTC, anishakj requested changes

2021-06-07 03:54 UTC, anishakj commented on charts/zookeeper-operator/templates/_helpers.tpl
> +      description: The number of ZooKeeper servers in the ensemble that are in a Ready sstate
Could you please correct the typo `sstate`

2021-06-07 04:18 UTC, anishakj approved these changes
LGTM

2021-06-07 04:27 UTC, SrishT approved these changes
LGTM

2021-06-07 04:58 UTC, merged