Added option to define templates for additional sidecars and volumes
pravega/zookeeper-operator pull request #352
Opened 2021-06-22 14:08 UTC by azun

### Change log description

Wrapped additionalSidecars and additionalVolumes inside named templates.

### Purpose of the change

Allows for defining templates for additionalSidecars/Volumes by extending the zookeeper-operator helm chart and overwriting `chart.*`.

2021-06-23 04:27 UTC, anishakj requested changes
what is this PR for? Could you please raise an issue corresponding to it?

2021-06-30 09:35 UTC, amuraru commented
@adapured please file an issue describe the use-case

2021-07-01 12:51 UTC, azun commented
> what is this PR for? Could you please raise an issue corresponding to it?

Raised https://github.com/pravega/zookeeper-operator/issues/358

2021-07-02 10:19 UTC, anishakj approved these changes
LGTM

2021-07-05 05:31 UTC, SrishT approved these changes
LGTM

2021-07-05 12:42 UTC, merged